Fix startup error introduced in 101fcdae7115e28ab64b89862b1658f432dbfd99
uncaughtException TypeError:
module$electron$utils.safe_decode_uri_component is not a function

Interesting that kondo doesn't catch invalid fns from js requires